menu:
# - {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv'}
# - {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/taehyunzzz'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/taehyun-kim-887601168/'}
- {icon: 'google scholar', link: 'https://scholar.google.com/citations?user=ZlCHolkAAAAJ&hl=ko&oi=sra'}
- {icon: 'orcid', link: 'https://orcid.org/0000-0003-3005-2066'}

contacts:
- {
    name: 'Taehyun Kim',
    title: 'Ph.D. Candidate',
    department: 'Electrical and Computer Engineering',
    institution: 'Seoul National University',
    institution_address: 'Gwanak-ro 1, Seoul, South Korea',
    phone: '(+82) 02-880-1825',
    email: 'taehyunzzz@snu.ac.kr / kimth@capp.snu.ac.kr',
    office: 'Inter-Unitersity Semiconductor Research Center Building 104-1',
    image: 'assets/img/contact.jpg'
  }
